#ifndef __MAGICNUMBERS_H__
#define __MAGICNUMBERS_H__

#include <limits>

#define NICK_MAX_LENGTH 9
#define AWAY_MAX_LENGTH 200
#define TOPIC_MAX_LENGTH 200
#define CHANNEL_NAME_MAX_LENGTH 32
#define KICKMSG_MAX_LENGTH 200
#define DEFAULT_MAX_CLIENTS 10
#define CLIENT_MAX_CHANNELS 5
#define SERVER_MAX_CLIENTS 10

#endif